version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Logging in to Docker Hub...
      - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
      - echo Fetching repository URL from SSM...
      - export REPO_URL=$(aws ssm get-parameter --name /plugfolio/GitRepoUrl --query Parameter.Value --output text)
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=build-$CODEBUILD_BUILD_NUMBER
      - echo IMAGE_TAG=$IMAGE_TAG
      - if [ -z "$IMAGE_TAG" ]; then echo "Error: IMAGE_TAG is empty"; exit 1; fi
      - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - export AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID:-$(aws sts get-caller-identity --query Account --output text)}
      - export IMAGE_REPO_NAME=${IMAGE_REPO_NAME:-plugfolio}
      - if [ -z "$AWS_DEFAULT_REGION" ] || [ -z "$AWS_ACCOUNT_ID" ] || [ -z "$IMAGE_REPO_NAME" ]; then echo "Error: Required environment variables are not set"; exit 1; fi

  build:
    commands:
      - ./scripts/build-docker.sh

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Storing image tag in SSM...
      - aws ssm put-parameter --name /plugfolio/DockerImageTag --value $IMAGE_TAG --type String --overwrite
      - 'echo "{\"docker_image_tag\": \"$IMAGE_TAG\"}" > output.json'

artifacts:
  files:
    - output.json
